package log

import "testing"

func Test1(_ *testing.T) {
	Error("fail")
}
